context:
  name: stacrs
  version: "0.5.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/stacrs-${{ version }}.tar.gz
  sha256: 17cc0766aa1061bd0dc584f340157e893a53c05e99182987c2382eaf6a429926

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip:
    - match(python, "<3.10")

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }} # needed to compile libduckdb-sys
    - ${{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - maturin >=1.7,<2.0
    - pip
    - python
  run:
    - python

tests:
  - python:
      imports:
        - stacrs
      pip_check: true

about:
  summary: A no-dependency Python package for STAC, using Rust under the hood.
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  homepage: https://www.gadom.ski/stacrs
  repository: https://github.com/gadomski/stacrs

extra:
  recipe-maintainers:
    - gadomski
    - weiji14
