context:
  name: stacrs
  version: "0.5.8"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/stacrs-${{ version }}.tar.gz
  sha256: 68ce670ec1d5eb20f40f41150bf47c77b265d7be35b81a1d36acb8f919de6bc4

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - maturin build --release -F duckdb-bundled --out .
    - ${{ PYTHON }} -m pip install stacrs*.whl -vv --no-deps --no-build-isolation
  skip:
    - match(python, "<3.10")

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }} # needed to compile libduckdb-sys
    - ${{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - maturin >=1.7,<2.0
    - pip
    - python
  run:
    - python

tests:
  - python:
      imports:
        - stacrs
      pip_check: true

about:
  summary: A Python package for STAC using Rust under the hood.
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  homepage: https://stac-utils.github.io/stacrs
  repository: https://github.com/stac-utils/stacrs

extra:
  recipe-maintainers:
    - gadomski
    - weiji14
